// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD33eOZYZ49nZ6252QKSZi5DMk4vw-moc',
    appId: '1:709065168042:web:8d4a0673ed9bcfed8dacd3',
    messagingSenderId: '709065168042',
    projectId: 'practiceauth-e9be8',
    authDomain: 'practiceauth-e9be8.firebaseapp.com',
    storageBucket: 'practiceauth-e9be8.firebasestorage.app',
    measurementId: 'G-0LQP19J22T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTo0PT7mpibSPT2vOMeuvT3tgTNhgCkRo',
    appId: '1:709065168042:android:d62890b098dc19aa8dacd3',
    messagingSenderId: '709065168042',
    projectId: 'practiceauth-e9be8',
    storageBucket: 'practiceauth-e9be8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCopBFUUt7bAnXQXvlOL-N5Oa0WUsDbqfA',
    appId: '1:709065168042:ios:262471d96eddf7ea8dacd3',
    messagingSenderId: '709065168042',
    projectId: 'practiceauth-e9be8',
    storageBucket: 'practiceauth-e9be8.firebasestorage.app',
    iosBundleId: 'com.example.authenticationPracticeProject',
  );
}
